acclen: 300000
# Coeffs should be a single number, or an array
# of 1024 numbers to set one coefficient per 8 channels.
coeffs: 100
# UDP port for 10GbE data
dest_port: 10000,10001,10002,10003,10004,10005,10006,10007
spectrometer_dest: 10.11.1.31
# Define which channels should be output
# over 10GbE in voltage dump mode.
voltage_output:
  start_chan: 768
  n_chans: 2560
  # Channels will be spread over the following
  # destinations so that the first n_chans // len(dests)
  # go to the first IP address, etc.
  dests:
      - 10.11.1.31
      - 10.11.1.31
      - 10.11.1.31
      - 10.11.1.31
      - 10.11.1.31
      - 10.11.1.31
      - 10.11.1.31
      - 10.11.1.31
      - 10.11.1.31
      - 10.11.1.31
      - 10.11.1.31
      - 10.11.1.31
      - 10.11.1.31
      - 10.11.1.31
      - 10.11.1.31
      - 10.11.1.31
      - 10.11.1.31
      - 10.11.1.31
      - 10.11.1.31
      - 10.11.1.31
  # Number of SNAP 10G outputs to use for voltages
  n_interfaces: 1
# All relevant IP/MAC mapping should be manually
# specified here
arp:
  # obs-node1
  10.11.1.31: 0xe41d2d24cac1
  # FRB nodes 1-6
  10.11.1.151: 0xe41d2d073fe1
  10.11.1.152: 0xe41d2d101dd1
  10.11.1.153: 0xe41d2d101a51
  10.11.1.154: 0xe41d2d18ccb1
  10.11.1.155: 0xe41d2d0ffa31
  10.11.1.156: 0x7cfe90921191
  # SNAPs 1-12 port 0
  10.11.1.161: 0x020202000001
  10.11.1.162: 0x020202000002
  10.11.1.163: 0x020202000003
  10.11.1.164: 0x020202000004
  10.11.1.165: 0x020202000005
  10.11.1.166: 0x020202000006
  10.11.1.167: 0x020202000007
  10.11.1.168: 0x020202000008
  10.11.1.169: 0x020202000009
  10.11.1.170: 0x02020200000a
  10.11.1.171: 0x02020200000b
  10.11.1.172: 0x02020200000c
  # SNAPs 1-12 port 1
  10.11.1.181: 0x020203000001
  10.11.1.182: 0x020203000002
  10.11.1.183: 0x020203000003
  10.11.1.184: 0x020203000004
  10.11.1.185: 0x020203000005
  10.11.1.186: 0x020203000006
  10.11.1.187: 0x020203000007
  10.11.1.188: 0x020203000008
  10.11.1.189: 0x020203000009
  10.11.1.190: 0x02020300000a
  10.11.1.191: 0x02020300000b
  10.11.1.192: 0x02020300000c
  # RFSOC
  10.11.1.201: 0x020203010001
  10.11.1.202: 0x020203010002
  10.11.1.203: 0x020203010003
  10.11.1.204: 0x020203010004
  10.11.1.205: 0x020203010005
# 10G port mappings based on SNAP hostname
interfaces:
  rfsoc1-ctrl-1:
    - 10.11.1.201
  rfsoc2-ctrl-1:
    - 10.11.1.202
  rfsoc3-ctrl-1:
    - 10.11.1.203
  frb-snap1-pi:
    - 10.11.1.161
    - 10.11.1.181
  frb-snap2-pi:
    - 10.11.1.162
    - 10.11.1.182
  frb-snap3-pi:
    - 10.11.1.163
    - 10.11.1.183
  frb-snap4-pi:
    - 10.11.1.164
    - 10.11.1.184
  frb-snap5-pi:
    - 10.11.1.165
    - 10.11.1.185
  frb-snap6-pi:
    - 10.11.1.166
    - 10.11.1.186
  frb-snap7-pi:
    - 10.11.1.167
    - 10.11.1.187
  frb-snap8-pi:
    - 10.11.1.168
    - 10.11.1.188
  frb-snap9-pi:
    - 10.11.1.169
    - 10.11.1.189
  frb-snap10-pi:
    - 10.11.1.160
    - 10.11.1.190
  frb-snap11-pi:
    - 10.11.1.171
    - 10.11.1.191
  frb-snap12-pi:
    - 10.11.1.172
    - 10.11.1.192
