acclen: 300000
# Coeffs should be a single number, or an array
# of 4096 numbers to set one coefficient per channel.
coeffs: 100
# UDP port for 10GbE data
dest_port: 10000
spectrometer_dest: 10.11.10.174
# Define which channels should be output
# over 10GbE in voltage dump mode.
voltage_output:
  start_chan: 0
  n_chans: 1024
  # Channels will be spread over the following
  # destinations so that the first n_chans // len(dests)
  # go to the first IP address, etc.
  dests:
      - 100.100.10.1
# All relevant IP/MAC mapping should be manually
# specified here
gateway: 100.100.11.1
arp:
  100.100.10.1: 0xa0481ce04198
  100.100.11.2: 0xa0481ce0419c
  100.100.10.88: 0x00394D031302
  100.100.11.89: 0x020a0b0c0d0e
interfaces:
  eth0_core: 100.100.10.88
  eth1_core: 100.100.11.89
